### ISSUE TITLE
Doesn't works with WordPress afterall.

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [oktadeveloper/okta-wordpress-sign-in-widget#14]
Error Details
=============
An error of type E_ERROR was caused in line 152 of the file /srv/htdocs/wp-content/plugins/okta-wordpress-sign-in-widget/okta-widget.php. Error message: Uncaught Error: Cannot use object of type WP_Error as array in /srv/htdocs/wp-content/plugins/okta-wordpress-sign-in-widget/okta-widget.php:152
Stack trace:
#0 /wordpress/core/5.2.3/wp-includes/class-wp-hook.php(286): Okta\OktaSignIn->loginAction('')
#1 /wordpress/core/5.2.3/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/5.2.3/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /wordpress/core/5.2.3/wp-login.php(478): do_action('login_init')
#4 {main}
  thrown

**Comment by aaronpk** [comment]
This should be fixed in the latest version.
