### ISSUE TITLE
Outdated auth script versions

### ISSUE THREAD

**Issue by Geshtu** [oktadeveloper/okta-wordpress-sign-in-widget#17]
Just a heads up for anyone looking at potentially using this repo:

- The templates > sign-out.php and includes > log-in-existing-session.php files are referencing okta-auth-js from v1.13.0, which was deprecated halfway through 2019, per https://github.com/okta/okta-auth-js. https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/2.4.0/okta-auth-js.min.js seems to be the newest.
- The templates > sign-in-form.php file is referencing okta-signin-widget from v2.6.0, which is now on v3.1.0, per https://github.com/okta/okta-signin-widget#contributing. I didn't see notes on the page related to versions.
- This plugin will return a NULL field for audit logging apps on user login. For the 3 I tried it brought me to an error page, but going to the /admin screen directly showed that login was indeed working.

The plugin hasn’t been updated for a while, but there are only ~100 lines of actual PHP in there. Didn't see any outdated WP functions or calls when looking through. So that's good, at least.

Edit: Added auth-js v2.4 CDN

**Comment by aaronpk** [comment]
This has been updated to the latest version of the Okta JS libraries.
