### ISSUE TITLE
Doesn't Work With WordPress 5.4

### ISSUE THREAD

**Issue by mbeinder** [oktadeveloper/okta-wordpress-sign-in-widget#20]
![Screen Shot 2020-03-31 at 11 04 20 PM](https://user-images.githubusercontent.com/50760632/78098232-0b525f80-73a4-11ea-98c4-bbba5a37ba10.png)
I just upgraded my site to wordpress 5.4 and now this plugin doesn't work. I tried installing the latest version of this plugin with the woocommerce corrections but the issue continues to persist.

I get an error from the plugin stating to make sure cookies are enabled. They are and the plugin still doesn't work.

///***EDIT***///
The issue may be coming from Okta itself. It appears that the resource the plugin is requesting cannot be found.

///***EDIT***///
Rolling back to WordPress version 5.3.2 resolves the issue. However it is not a long term solution. I am not familiar enough with this plugin to fix the issue and submit a pull request. However I'll contribute anyway I can.

**Comment by EricWoodlandBF** [comment]
+1 for this @mbeinder. Cannot get this working on a new WP 5.4 instance. Have no ability to roll-back to 5.3.2.

**Comment by aaronpk** [comment]
I just did a big overhaul of the plugin and tested it in 5.4!
