### ISSUE TITLE
Login fails when allow native login option is disabled

### ISSUE THREAD

**Issue by neilsai** [oktadeveloper/okta-wordpress-sign-in-widget#23]
Really liked the simpler configuration for the new version!   Unfortunately i am having problems getting it to work with my okta dev account and that has prevented us from upgrading so far:

When i configure the new version of the plugin using the client ID for an SPA okta application setup in my dev account, the plugin works ok but only if i select the option to allow native wordpress logins (which we don't want in production).

The other less significant issue is the need to put the client ID in two places in the plugin settings screen:

1. i put the same client ID in _both_ the "Sign-in Widget Client ID" _and_ the "Client ID" fields - this is a little confusing - perhaps better to have an either / or configuration option?
2. i check the checkbox marked "Allow Native WordPress Login".

Please let me know if i am doing something wrong or if you have anyone else with the same issue. 

Cheers,
Neil

**Comment by aaronpk** [comment]
Sorry about that! There was a javascript bug when wordpress logins were disabled. That should be fixed now.

As for the client ID issue, you actually need to create two separate clients in Okta, you can't use the same client ID for both. The instructions on the configuration page should have walked you through that.

**Comment by neilsai** [comment]
Hi Aaron,

This is working perfectly now.   Thanks for updating the plugin so quickly.

It actually still works ok for me if I set both client IDs to be my SPA app (and leave client secret blank).   I also configured a separate OAuth service app as well and changed the settings as described in the config page help and this also works.

We have quite a number of wordpress applications running on Pantheon.  My plan is to create a single Service App that can be used by all of the sites and then an SPA app for each one individually.  I am testing this out now with a second test site..  Does this approach sound reasonable?

Any thoughts on why the same client ID for both configuration settings works for me?

Cheers,
Neil

**Comment by neilsai** [comment]
Hi Aaron,

Strangely – I set up a second site basically identical to the first and I can’t get this one to work with several different configuration options.  The first site continues to work however.   I have tried to compare and I can’t see any differences between the two.   The main difference was the first one was installed on the old version and I just updated the code via a git push.   For the second site the plugin was installed and activated with the latest code.

What I see when attempting to log in is no response from the api request:
[cid:image003.jpg@01D6553B.C8D9B2B0]
[cid:image004.jpg@01D6553B.C8D9B2B0]

Here are also some logs from the second site:

[08-Jul-2020 01:29:24 UTC] PHP Warning:  session_start(): Cannot start session when headers already sent in /srv/bindings/750ed78356c84adbb7ed47a3d0818156/code/wp-content/plugins/okta-wordpress-sign-in-widget/okta-widget.php on line 59
[08-Jul-2020 02:30:46 UTC] PHP Warning:  session_start(): Cannot start session when headers already sent in /srv/bindings/750ed78356c84adbb7ed47a3d0818156/code/wp-content/plugins/okta-wordpress-sign-in-widget/okta-widget.php on line 59
[08-Jul-2020 03:29:01 UTC] PHP Warning:  session_start(): Cannot start session when headers already sent in /srv/bindings/750ed78356c84adbb7ed47a3d0818156/code/wp-content/plugins/okta-wordpress-sign-in-widget/okta-widget.php on line 59
[08-Jul-2020 05:12:36 UTC] PHP Notice:  Constant WP_TEMP_DIR already defined in phar:///opt/pantheon/wp-cli2/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code on line 84
[08-Jul-2020 05:12:36 UTC] PHP Notice:  Constant WPLANG already defined in phar:///opt/pantheon/wp-cli2/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code on line 133
[08-Jul-2020 05:12:36 UTC] PHP Warning:  session_set_save_handler(): Cannot change save handler when headers already sent in /srv/bindings/750ed78356c84adbb7ed47a3d0818156/code/wp-content/plugins/wp-native-php-sessions/pantheon-sessions.php on line 171
[08-Jul-2020 05:12:36 UTC] PHP Warning:  session_start(): Cannot start session when headers already sent in /srv/bindings/750ed78356c84adbb7ed47a3d0818156/code/wp-content/plugins/okta-wordpress-sign-in-widget/okta-widget.php on line 59

Cheers,
Neil

From: Neil Kenrick
Sent: Wednesday, 8 July 2020 11:23 AM
To: oktadeveloper/okta-wordpress-sign-in-widget <reply@reply.github.com>; oktadeveloper/okta-wordpress-sign-in-widget <okta-wordpress-sign-in-widget@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [oktadeveloper/okta-wordpress-sign-in-widget] Login fails when allow native login option is disabled (#23)

Hi Aaron,

This is working perfectly now.   Thanks for updating the plugin so quickly.

It actually still works ok for me if I set both client IDs to be my SPA app (and leave client secret blank).   I also configured a separate OAuth service app as well and changed the settings as described in the config page help and this also works.

We have quite a number of wordpress applications running on Pantheon.  My plan is to create a single Service App that can be used by all of the sites and then an SPA app for each one individually.  I am testing this out now with a second test site..  Does this approach sound reasonable?

Any thoughts on why the same client ID for both configuration settings works for me?

Cheers,
Neil

**Comment by aaronpk** [comment]
It looks like the images didn't come though. Can you try visiting this issue on GitHub and uploading the images there?

I also just pushed a change to remove the secondary client ID/secret so it should be easier to set up now.

**Comment by neilsai** [comment]
Hi Aaron,

I did a bit more investigation today.   The bug that prevented sign on when 'allow native login' is disabled is definitely fixed.   also thanks for removing the need for the service application.

The issue seems to be - and i have tested this on a couple of sites and okta apps - is that the widget relies on the Base URL being configured in Okta.   Now the Base URL is not available when using the new UI - it is only available when using the older developer console.  Even then it is only available when creating a new app - not when editing an existing app.

I am setting the URLs as follows to get it to work:

Base URIs: https://dev-nk-okta-test-two.pantheonsite.io/
Login redirect URIs: https://dev-nk-okta-test-two.pantheonsite.io/wp-login.php
Logout redirect URIs: https://dev-nk-okta-test-two.pantheonsite.io/

<img width="617" alt="config to get it to work" src="https://user-images.githubusercontent.com/44352737/87107096-3cdf9e80-c2a2-11ea-9c14-285981aa137e.png">

Without setting base URIs i get an error as described above.  

I will attach some screen shots here now as they didn't come through

Login error message that comes up if Base URI is not configured (because using the new UI):
![login-error-messgae](https://user-images.githubusercontent.com/44352737/87107214-85975780-c2a2-11ea-8257-decd3d144c8e.png)

Dev console (chrome) error when this occurs:
![dev-console-error](https://user-images.githubusercontent.com/44352737/87107237-9778fa80-c2a2-11ea-8b5a-41b9558ee50f.png)

**Comment by aaronpk** [comment]
Alright, that's confusing I agree.

I just changed things around again with the plugin to remove a config option. Now you only need to provide the Issuer URI when configuring the plugin (You'll need to update the plugin config again). You should be able to find the issuer URI by following the instructions on the configuration screen. 

Let me know if this is more straightforward!

**Comment by neilsai** [comment]
Works great now - thanks for picking up these issues for us.  

Cheers,
Neil
