### ISSUE TITLE
State error. Make sure cookies are enabled

### ISSUE THREAD

**Issue by rr128** [oktadeveloper/okta-wordpress-sign-in-widget#24]
We received the following error when use this Okta widget with our WP environment.

_State error. Make sure cookies are enabled_

We are able to login successful, but after the login we received that error.  Anything we need to update on our end?

**Comment by aaronpk** [comment]
Can you confirm that the URL you start on matches the same origin as the redirect URL?

For example, starting at `http://127.0.0.1:8080/` and being redirected to `http://localhost:8080/` will fail (correctly) because cookies aren't shared between those two domains.

**Comment by rr128** [comment]
Starting url is https://localhost/site/wp-login.php and then gets redirected to https://localhost/site/wp-admin.php

**Comment by aaronpk** [comment]
Can you clarify where this error message appears and what the URL in the address bar is when you see it? A screenshot would be helpful for context.

**Comment by rr128** [comment]
error = State error. Make sure cookies are enabled.  I'll message a screenshot.

**Comment by aaronpk** [comment]
Thanks, I realized this error message is from a previous version of the plugin. The current version works a slightly different way and doesn't have this error message in it anymore. Could you update to the latest code and try again? I fixed a few other related problems as well so it should be more stable now.

**Comment by rr128** [comment]
We updated the latest code and now we get the following error:
<img width="1310" alt="Screen Shot 2020-07-14 at 9 31 09 AM" src="https://user-images.githubusercontent.com/38516345/87431708-04e39e80-c5b5-11ea-8740-53d7e6d673a1.png">

**Comment by rr128** [comment]
Got it to work. I created a new app and selected SPA as the platform.  After inputting all the necessary data, everything work as expected. Thanks!
