### ISSUE TITLE
Posting an example structure of the env.php file

### ISSUE THREAD

**Issue by jbakalar-optimist** [oktadeveloper/okta-wordpress-sign-in-widget#26]
Hi,

I uploaded the plugin to my WordPress site and wanted to prepare the env.php . However, I do not see the example.env.php anywhere to know how it should look like. Could you upload it to the repo, please? Thank you.

Jan

**Comment by aaronpk** [comment]
Sorry, the blog post that you read the instructions on is out of date, this plugin has been updated to not require an env file anymore!
