### ISSUE TITLE
Web Application Client Support

### ISSUE THREAD

**Issue by neilsai** [oktadeveloper/okta-wordpress-sign-in-widget#27]
Hi Aaron,

As mentioned on the previous issue I am opening this as our okta account doesn't support SPA clients which the latest version of this plugin now uses.   We are ok with the Web Application client which uses the regular Authorization code flow but the PKCE option for SPAs is not supported.

It would be great if the plugin could support that option, otherwise we will probably have to look at more generic OAuth plugins for this instead. 

Best regards,
Neil

**Comment by aaronpk** [comment]
If you have the option of using a generic OIDC plugin for wordpress and using the redirect approach I would recommend that instead. This is specifically to embed the sign-in widget in the wordpress page to avoid redirecting people away from wordpress.

**Comment by neilsai** [comment]
Hi Aaron,   

Yes - thanks we are now using the WP SAML plugin which is working really well with the okta account for our purposes.   I think this plugin was the wrong option for us.   Thanks for all your help though.

Cheers,
Neil
