### ISSUE TITLE
Redirect to Okta-hosted login page

### ISSUE THREAD

**Issue by RafaelMiquelino** [oktadeveloper/okta-wordpress-sign-in-widget#32]
Is it possible to redirect to the okta-hosted login widget instead of serving the widget locally? I have external IDP (google and facebook) configured on my login and it is all set on my okta-hosted login page and I'd rather redirect than forking this repository and adjusting it by my own.\

By the way, thanks for the plugin. That's quite useful.

**Comment by aaronpk** [comment]
If you're going to redirect to Okta then you're probably better off using a generic OIDC plugin instead of this one. This one is really optimized just to embed the Okta sign-in page.
