### ISSUE TITLE
Getting 401 Error, Do I need to create .env.php file?

### ISSUE THREAD

**Issue by debabratakarfa** [oktadeveloper/okta-wordpress-sign-in-widget#34]
Hey
After successful login, I am getting 401 error.

I wish to know, Do I need to create .env.php file to Client ID and Secret? 

And if so, Can you share Define param name? 

Thanks

**Comment by aaronpk** [comment]
We changed the plugin to define all configuration within the wordpress screen itself instead of in a configuration file. Once you install and activate the plugin, visit the plugin’s settings page and it will tell you everything you need to do to set it up.
