### ISSUE TITLE
`Policy evaluation failed for this request. please check the policy configurations.` error

### ISSUE THREAD

**Issue by aolin480** [oktadeveloper/okta-wordpress-sign-in-widget#35]
I am getting the following GET param error message when I try signing in, and it goes to the `/wp/wp-login.php?` page, which is throwing a forbidden error. I am not too sure what else I need to set, in terms of "policy." I tried redo'ing the configuration, creating a new application / API, etc but this is where I am currently at right now.

`/wp/wp-login.php?state=3iNxeK8PFjDg8DZ5M8tc3ySxf8ccUdE0YMWkUYbM8TLBQJfOoMFiz2QQGHGhjZTg&error=access_denied&error_description=Policy+evaluation+failed+for+this+request%2C+please+check+the+policy+configurations.`

Thanks in advance!

**Comment by aaronpk** [comment]
It sounds like maybe your user isn't assigned this app in Okta? I don't remember the exact reason this error would be returned by Okta but that would be my first thought

**Comment by aolin480** [comment]
Okay. So unless I spent too much time on this, and glossed over this tab, I now see a Access Policies tab when editing my Authorized Server. I went ahead and added a new policy, and now when I try to log in, I no longer get that error message, but after I authorize my scopes (email/openid), it just redirects to `/wp-login.php` and the page is blank 🤔  If I refresh the page, it brings me back to the Okta sign-in screen again

**Comment by aolin480** [comment]
So the plot thickens 😬  I am seeing the URL change when I try to sign in, and I am getting the following `GET` parameters, which I do not see references to in the plugin code. Looks like the plugin is looking for things like `redirect_to` and `log_in_from_id_token` but I am getting the following from Okta when trying to process the sign-in

`/wp/wp-login.php?code=6B3T8ZRfbOjWF5xqBWQ4Suv8zYDwXsyQkO02QggsBFw&state=Krpf4oUxsbofbNzpH5Wvws0bbTYVkr11fyLfBhNVjNSw44u7caoGtanA9fHa69VS`

**Comment by aaronpk** [comment]
Did you create the application in Okta as a “SPA” app?

**Comment by aolin480** [comment]
If you're talking about this step, I chose Web 😬  So I should be setting it as SPA?

![image](https://user-images.githubusercontent.com/1616101/99422302-073c6900-28c5-11eb-8220-4384717407cf.png)

**Comment by aaronpk** [comment]
Yep! Looks like I should add that to the readme, but it does say that in the wordpress configuration screen.

**Comment by aolin480** [comment]
Yeah, I definitely glossed over that term 😭  I can now log into my site! 

From one Aaron to another, I appreciate your help on this! Thanks for your work on this plugin! 👏🏽
